version: '2.1'

services:
  ecare:
    network_mode: bridge

    image: ecare
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ecare
    ports:
      - 8080:8080
    expose:
            - 8080
    depends_on:
      - db
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_PROFILES_ACTIVE=dev
      
          
  db:
    network_mode: bridge

    image: 'postgres:13.1-alpine'    
    container_name: db    
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
      - dbhost=db
       
 